# Generated by Django 6.0.4 on 2026-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_warehouse_stock_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock_movement",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
