# Generated by Django 6.0.4 on 2026-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_stock_level_alter_stock_movement_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stock_Movement",
            new_name="StockMovement",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock_level",
            new_name="stock",
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
