# Generated by Django 6.0.4 on 2026-05-13 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_stock_movement_stockmovement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
