# Generated by Django 6.0.4 on 2026-05-13 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_stockmovement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
