# Generated by Django 6.0.4 on 2026-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_stockmovement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="remaining_stock",
            field=models.PositiveIntegerField(default=999999, editable=False),
            preserve_default=False,
        ),
    ]
