
CREATE TABLE PRODUCT(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    FOREIGN KEY (category) REFERENCES CATEGORY(name),
    unit_price DECIMAL(10,2) NOT NULL,
    reorder_level DECIMAL(10,2) NOT NULL,
    description TEXT NOT NULL
)

